# Generated by Django 2.2 on 2023-01-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentSharingService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='PostItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='ContentSharingService.PostItem'),
        ),
    ]
